### ISSUE TITLE
Getting 500 Interval Server Error when invoking 'New Consent at specified Data Holder' postman request

### ISSUE THREAD

**Issue by narramadan** [Regional-Australia-Bank/ADR-Gateway#11]
Hi,

I booted up docker images and started invoking postman tests by importing the postman collection as documented in README.md.

I am getting `500 Internal Server Error` when invoking `New Consent at specified Data Holder` request.

![image](https://user-images.githubusercontent.com/3821456/93653048-9a3e5b80-fa5a-11ea-91ef-8144ea430fac.png)

Is there any specific headers that should be provided ?

There are no logs captured on what went wrong written to docker-compose logs apart from what I see below:

`docker-compose -f ./examples/deployment/docker/docker-compose.yml logs -f`

```
b_1                | 2020-09-18 22:56:22.049 UTC [1] LOG:  starting PostgreSQL 12.2 (Debian 12.2-2.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
db_1                | 2020-09-18 22:56:22.050 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1                | 2020-09-18 22:56:22.050 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1                | 2020-09-18 22:56:22.139 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1                | 2020-09-18 22:56:22.387 UTC [65] LOG:  database system was shut down at 2020-09-18 22:56:21 UTC
db_1                | 2020-09-18 22:56:22.520 UTC [1] LOG:  database system is ready to accept connections
docker_adr-db-migrate_1 exited with code 0
adr-frontend_1      | (node:1) UnhandledPromiseRejectionWarning: Error: connect EHOSTUNREACH 172.18.0.12:5432
adr-frontend_1      |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16)
adr-frontend_1      | (Use `node --trace-warnings ...` to show where the warning was created)
adr-frontend_1      | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
adr-frontend_1      | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
mock-dh_1           | (node:1) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND db
mock-dh_1           |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
mock-dh_1           | (Use `node --trace-warnings ...` to show where the warning was created)
mock-dh_1           | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
mock-dh_1           | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
adr-backend_1       | (node:1) UnhandledPromiseRejectionWarning: Error: connect EHOSTUNREACH 172.18.0.12:5432
adr-backend_1       |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16)
adr-backend_1       | (Use `node --trace-warnings ...` to show where the warning was created)
adr-backend_1       | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
adr-backend_1       | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
adr-backend_1       | (node:1) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
adr-housekeeper_1   | (node:1) UnhandledPromiseRejectionWarning: Error: connect EHOSTUNREACH 172.18.0.12:5432
adr-housekeeper_1   |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16)
adr-housekeeper_1   | (Use `node --trace-warnings ...` to show where the warning was created)
adr-housekeeper_1   | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
adr-housekeeper_1   | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
adr-housekeeper_1   | (node:1) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
mock-register_1     | WARNING: x-forwarded-proto header not detected for an https issuer, you must configure your ssl offloading proxy and the provider, see documentation for more details: https://github.com/panva/node-oidc-provider/tree/v6.29.3/docs/README.md#trusting-tls-offloading-proxies
```
Thanks,
Madan N

**Comment by pcurtisrab** [comment]
Hi @narramadan,

Thanks for contributing this issue!

It looks like you are doing everything correctly with Postman. After investigating myself I found there was a wrong configuration in `examples/deployment/docker/sandbox.env` in relation to PAR.

However, I also wonder if you somehow got yourself in a bad state with the Docker containers. From your log files it looks like _adr-db-migrate_ has run (and exited) before the database was ready. I have addressed this by configuring that container to restart "on-failure". 

Could you please try again from a fresh state with Docker?
1. Pull the latest commit
2. Please delete the volumes, images and containers created for adr-gateway
3. Run `npm run build:docker`
4. Run `npm run start:docker`
5. Look for loogging from the _adr-db-migrate_ service
6. Login to adminer at `http://localhost:8080` to verify the database is available and has been populated. You can use this configuration `{"type":"postgres","host":"db","username":"postgres","password":"example","database":"adr-sandbox"}`
7. Try the POST consents API call again

If there is still a problem, please reopen this issue.

**Comment by narramadan** [comment]
Hi @pcurtisrab ,

Still the same. 

* Deleted all the images and containers created for adr-gateway.
* Fresh checkout of master
* Run npm commands to build the images.
* Attached the logs captured from docker-compose. 
* Attached snapshot of adminer listing tables under adr-sandbox

**Q)** Is there a way we can enable Debug/Info statements captured in docker-compose logs ?

[docker-compose startup logs](https://github.com/Regional-Australia-Bank/ADR-Gateway/files/5253686/startup.log)

![image](https://user-images.githubusercontent.com/3821456/93737024-59467280-fc25-11ea-924e-0ec4dc2deb83.png)

![image](https://user-images.githubusercontent.com/3821456/93737330-42545000-fc26-11ea-9eea-93e38dfae250.png)

Thanks,
Madan N

**Comment by pcurtisrab** [comment]
Hi @narramadan, 

Yes, you can edit `sandbox.env` at line 8 with `LOG_LEVEL=debug`. Please try that.

**Comment by pcurtisrab** [comment]
Hi @narramadan ,

I know what the problem is (I think).

I did not completely correct line 58 in sandbox.env. It is currently

```
DH_OIDC_PAR_ENDPOINT=https://localhost:10202/par
```
but should be
```
DH_OIDC_PAR_ENDPOINT=https://mock-infra:10202/par
```

Please try that and let me know how it goes.

**Comment by narramadan** [comment]
Hi @pcurtisrab ,

Its still the same.

Changed line 58 in sandbox.env and completely deleted images, build and started the services.

And changing `LOG_LEVEL=debug` is not capturing any debug or info logs to see if postman call is reaching the code.

```
RequestConsent = async (p: ConsentRequestParams) =>{
  
  this.logger.info(`Request for new consent at data holder: ${p.dataholderBrandId} for software product: ${p.productKey}`);
  
  let requestor = this.connector.GetAuthorizationRequest(p);
  return (await requestor.Evaluate())
```

**Comment by pcurtisrab** [comment]
Hi @narramadan,

That's interesting. I have a few ideas:
- I *feel* like I have seen some of this not-logging strangeness. It seemed related to the docker environment somehow. It might be worth following the PM2 instructions to see if they work. That would give us a useful data point.
- Are the other "adr-frontend" endpoints working. I would be interested to know the status of http://localhost:8101/jwks and https://localhost:9101/jwks, as well as "GET dataholders"
- There is the possibility of attaching a debugger.

On the other hand it may be easier to set up a screen sharing session to get to the bottom of it. Feel free to reach out to me via email and we can organise that if you'd like.

**Comment by narramadan** [comment]
Sure. Will try and reach back.

Whats the email address and best time we can catch up ?

**Comment by pcurtisrab** [comment]
I have been able to reproduce this: If the database is not up when the dependent service starts (e.g. adr-backend, mock-dh-server), then that service will not recover, even when the database comes back up.

I regard this as an important issue, even if it can be fixed by changing the load order. It begs the question, also, if the database connection will recover if the database has a momentary outage while the dependent services are already successfully started.

I will regard this problem as solved when:
- Promise rejections successfully cause a docker container to finish
- Docker containers restart on the error condition above
- It can be shown that dependent services recover after a momentary outage of the database.

Great find, @narramadan :)

**Comment by pcurtisrab** [comment]
This has been solved with #12 at https://github.com/Regional-Australia-Bank/ADR-Gateway/commit/248595e0a9865437e2851fe8da4df22902b9476c.

#13 has been raised to deal with the root cause issue.
